"""Version con el completado nullable.

Revision ID: 2a2f39a5e247
Revises: 85f7cd5bd997
Create Date: 2022-11-14 16:26:42.247566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2f39a5e247'
down_revision = '85f7cd5bd997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completado',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completado',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
