"""empty message

Revision ID: 5470e7736a2b
Revises: 58630ae104c2
Create Date: 2022-11-14 15:07:57.811936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5470e7736a2b'
down_revision = '58630ae104c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completado', sa.Boolean(), nullable=True))
        op.execute('UPDATE todos SET completado = False WHERE completado IS NULL;')
        op.alter_column('todos', 'completado', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completado')

    # ### end Alembic commands ###
